// =============================================================================
// (c) Copyright Sanskar Yadav. All rights reserved.
// Made by Sanskar Yadav.
// =============================================================================

/**
 * FILE: constants/themes-extended.ts
 * PURPOSE: Comprehensive theme definitions for MeTodo app
 *
 * DESCRIPTION:
 * Defines 50+ professional themes with carefully selected color palettes.
 * Each theme includes primary, secondary, background, and accent colors.
 *
 * THEMES INCLUDED:
 * - 10 Light Themes
 * - 10 Dark Themes
 * - 10 Vibrant Themes
 * - 10 Pastel Themes
 * - 10 Professional Themes
 */

export interface ThemeColors {
  primary: string;
  secondary: string;
  background: string;
  surface: string;
  foreground: string;
  muted: string;
  border: string;
  success: string;
  warning: string;
  error: string;
  accent: string;
}

export interface Theme {
  id: string;
  name: string;
  description: string;
  colors: ThemeColors;
  isDark: boolean;
  category: 'light' | 'dark' | 'vibrant' | 'pastel' | 'professional';
}

// Light Themes
const lightThemes: Theme[] = [
  {
    id: 'light_default',
    name: 'Default Light',
    description: 'Clean and minimal light theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#0a7ea4',
      secondary: '#0891b2',
      background: '#ffffff',
      surface: '#f5f5f5',
      foreground: '#11181c',
      muted: '#687076',
      border: '#e5e7eb',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#0a7ea4',
    },
  },
  {
    id: 'light_ocean',
    name: 'Ocean Breeze',
    description: 'Calming ocean-inspired theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#0369a1',
      secondary: '#06b6d4',
      background: '#f0f9ff',
      surface: '#e0f2fe',
      foreground: '#0c2d4a',
      muted: '#475569',
      border: '#bae6fd',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#06b6d4',
    },
  },
  {
    id: 'light_forest',
    name: 'Forest Green',
    description: 'Nature-inspired green theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#059669',
      secondary: '#10b981',
      background: '#f0fdf4',
      surface: '#dcfce7',
      foreground: '#064e3b',
      muted: '#6b7280',
      border: '#bbf7d0',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#10b981',
    },
  },
  {
    id: 'light_sunset',
    name: 'Sunset Gold',
    description: 'Warm sunset-inspired theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#d97706',
      secondary: '#f59e0b',
      background: '#fffbeb',
      surface: '#fef3c7',
      foreground: '#78350f',
      muted: '#6b7280',
      border: '#fde68a',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#f59e0b',
    },
  },
  {
    id: 'light_lavender',
    name: 'Lavender Dream',
    description: 'Soft lavender theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#7c3aed',
      secondary: '#a78bfa',
      background: '#faf5ff',
      surface: '#f3e8ff',
      foreground: '#4c1d95',
      muted: '#6b7280',
      border: '#e9d5ff',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#a78bfa',
    },
  },
  {
    id: 'light_rose',
    name: 'Rose Pink',
    description: 'Elegant rose theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#e11d48',
      secondary: '#f43f5e',
      background: '#fff1f2',
      surface: '#ffe4e6',
      foreground: '#831843',
      muted: '#6b7280',
      border: '#fbcfe8',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#f43f5e',
    },
  },
  {
    id: 'light_cyan',
    name: 'Cyan Cool',
    description: 'Cool cyan theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#0891b2',
      secondary: '#06b6d4',
      background: '#ecf0f1',
      surface: '#e0f2fe',
      foreground: '#164e63',
      muted: '#6b7280',
      border: '#cffafe',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#06b6d4',
    },
  },
  {
    id: 'light_amber',
    name: 'Amber Warm',
    description: 'Warm amber theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#b45309',
      secondary: '#d97706',
      background: '#fffbeb',
      surface: '#fef3c7',
      foreground: '#78350f',
      muted: '#6b7280',
      border: '#fcd34d',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#d97706',
    },
  },
  {
    id: 'light_teal',
    name: 'Teal Fresh',
    description: 'Fresh teal theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#0d9488',
      secondary: '#14b8a6',
      background: '#f0fdfa',
      surface: '#ccfbf1',
      foreground: '#134e4a',
      muted: '#6b7280',
      border: '#99f6e4',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#14b8a6',
    },
  },
  {
    id: 'light_indigo',
    name: 'Indigo Deep',
    description: 'Deep indigo theme',
    isDark: false,
    category: 'light',
    colors: {
      primary: '#4f46e5',
      secondary: '#6366f1',
      background: '#f0f4ff',
      surface: '#e0e7ff',
      foreground: '#1e1b4b',
      muted: '#6b7280',
      border: '#c7d2fe',
      success: '#22c55e',
      warning: '#f59e0b',
      error: '#ef4444',
      accent: '#6366f1',
    },
  },
];

// Dark Themes
const darkThemes: Theme[] = [
  {
    id: 'dark_default',
    name: 'Default Dark',
    description: 'Clean and minimal dark theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#0a7ea4',
      secondary: '#0891b2',
      background: '#151718',
      surface: '#1e2022',
      foreground: '#ecedee',
      muted: '#9ba1a6',
      border: '#334155',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#0a7ea4',
    },
  },
  {
    id: 'dark_midnight',
    name: 'Midnight Blue',
    description: 'Deep midnight blue dark theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#0369a1',
      secondary: '#06b6d4',
      background: '#0f172a',
      surface: '#1e293b',
      foreground: '#f1f5f9',
      muted: '#94a3b8',
      border: '#334155',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#06b6d4',
    },
  },
  {
    id: 'dark_forest',
    name: 'Dark Forest',
    description: 'Dark forest green theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#059669',
      secondary: '#10b981',
      background: '#0f2818',
      surface: '#1a3a2a',
      foreground: '#ecfdf5',
      muted: '#86efac',
      border: '#365a40',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#10b981',
    },
  },
  {
    id: 'dark_sunset',
    name: 'Dark Sunset',
    description: 'Dark sunset orange theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#d97706',
      secondary: '#f59e0b',
      background: '#1f1410',
      surface: '#3a2817',
      foreground: '#fef3c7',
      muted: '#fcd34d',
      border: '#5a3a1f',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#f59e0b',
    },
  },
  {
    id: 'dark_purple',
    name: 'Dark Purple',
    description: 'Dark purple theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#7c3aed',
      secondary: '#a78bfa',
      background: '#1f1033',
      surface: '#2e1a47',
      foreground: '#f3e8ff',
      muted: '#d8b4fe',
      border: '#4c1d95',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#a78bfa',
    },
  },
  {
    id: 'dark_rose',
    name: 'Dark Rose',
    description: 'Dark rose theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#e11d48',
      secondary: '#f43f5e',
      background: '#1f0f1a',
      surface: '#3a1f2e',
      foreground: '#ffe4e6',
      muted: '#fbcfe8',
      border: '#831843',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#f43f5e',
    },
  },
  {
    id: 'dark_cyan',
    name: 'Dark Cyan',
    description: 'Dark cyan theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#0891b2',
      secondary: '#06b6d4',
      background: '#0f2f35',
      surface: '#164e63',
      foreground: '#cffafe',
      muted: '#67e8f9',
      border: '#0c4a6e',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#06b6d4',
    },
  },
  {
    id: 'dark_amber',
    name: 'Dark Amber',
    description: 'Dark amber theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#b45309',
      secondary: '#d97706',
      background: '#1f1410',
      surface: '#3a2817',
      foreground: '#fef3c7',
      muted: '#fcd34d',
      border: '#78350f',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#d97706',
    },
  },
  {
    id: 'dark_teal',
    name: 'Dark Teal',
    description: 'Dark teal theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#0d9488',
      secondary: '#14b8a6',
      background: '#0f2f2e',
      surface: '#134e4a',
      foreground: '#ccfbf1',
      muted: '#99f6e4',
      border: '#0d4a48',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#14b8a6',
    },
  },
  {
    id: 'dark_indigo',
    name: 'Dark Indigo',
    description: 'Dark indigo theme',
    isDark: true,
    category: 'dark',
    colors: {
      primary: '#4f46e5',
      secondary: '#6366f1',
      background: '#0f0a1f',
      surface: '#1e1b4b',
      foreground: '#e0e7ff',
      muted: '#c7d2fe',
      border: '#3730a3',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#6366f1',
    },
  },
];

// Vibrant Themes
const vibrantThemes: Theme[] = [
  {
    id: 'vibrant_neon',
    name: 'Neon Glow',
    description: 'Vibrant neon colors',
    isDark: true,
    category: 'vibrant',
    colors: {
      primary: '#ff006e',
      secondary: '#00f5ff',
      background: '#0a0e27',
      surface: '#1a1f3a',
      foreground: '#ffffff',
      muted: '#a0aec0',
      border: '#2d3748',
      success: '#39ff14',
      warning: '#ffed4e',
      error: '#ff0040',
      accent: '#00f5ff',
    },
  },
  {
    id: 'vibrant_cyber',
    name: 'Cyberpunk',
    description: 'Cyberpunk inspired theme',
    isDark: true,
    category: 'vibrant',
    colors: {
      primary: '#ff10f0',
      secondary: '#00ff88',
      background: '#0d0221',
      surface: '#1a0033',
      foreground: '#ffffff',
      muted: '#888899',
      border: '#330066',
      success: '#00ff88',
      warning: '#ffaa00',
      error: '#ff0055',
      accent: '#00ff88',
    },
  },
  {
    id: 'vibrant_sunset_fire',
    name: 'Sunset Fire',
    description: 'Fiery sunset colors',
    isDark: false,
    category: 'vibrant',
    colors: {
      primary: '#ff6b35',
      secondary: '#ff8c42',
      background: '#fff8f3',
      surface: '#ffe8d6',
      foreground: '#1a1a1a',
      muted: '#666666',
      border: '#ffccb3',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#ff4444',
      accent: '#ff8c42',
    },
  },
  {
    id: 'vibrant_electric',
    name: 'Electric Blue',
    description: 'Electric blue theme',
    isDark: true,
    category: 'vibrant',
    colors: {
      primary: '#0080ff',
      secondary: '#00ffff',
      background: '#000033',
      surface: '#001a4d',
      foreground: '#ffffff',
      muted: '#8899cc',
      border: '#003366',
      success: '#00ff00',
      warning: '#ffff00',
      error: '#ff0000',
      accent: '#00ffff',
    },
  },
  {
    id: 'vibrant_magenta',
    name: 'Magenta Dream',
    description: 'Vibrant magenta theme',
    isDark: true,
    category: 'vibrant',
    colors: {
      primary: '#ff00ff',
      secondary: '#ff1493',
      background: '#1a001a',
      surface: '#330033',
      foreground: '#ffffff',
      muted: '#cc99ff',
      border: '#660066',
      success: '#00ff00',
      warning: '#ffff00',
      error: '#ff0000',
      accent: '#ff1493',
    },
  },
  {
    id: 'vibrant_tropical',
    name: 'Tropical Vibes',
    description: 'Tropical bright colors',
    isDark: false,
    category: 'vibrant',
    colors: {
      primary: '#ff006e',
      secondary: '#00d9ff',
      background: '#fffacd',
      surface: '#ffebcd',
      foreground: '#1a1a1a',
      muted: '#666666',
      border: '#ffd700',
      success: '#00ff00',
      warning: '#ff8c00',
      error: '#ff0000',
      accent: '#00d9ff',
    },
  },
  {
    id: 'vibrant_plasma',
    name: 'Plasma Energy',
    description: 'Plasma energy theme',
    isDark: true,
    category: 'vibrant',
    colors: {
      primary: '#ff0080',
      secondary: '#ff8000',
      background: '#0a0000',
      surface: '#2a0000',
      foreground: '#ffffff',
      muted: '#ff6666',
      border: '#660000',
      success: '#00ff00',
      warning: '#ffff00',
      error: '#ff0000',
      accent: '#ff8000',
    },
  },
  {
    id: 'vibrant_aqua',
    name: 'Aqua Splash',
    description: 'Aqua splash theme',
    isDark: false,
    category: 'vibrant',
    colors: {
      primary: '#00bfff',
      secondary: '#00ced1',
      background: '#e0ffff',
      surface: '#afeeee',
      foreground: '#000033',
      muted: '#333366',
      border: '#7fffd4',
      success: '#00ff00',
      warning: '#ff8c00',
      error: '#ff0000',
      accent: '#00ced1',
    },
  },
  {
    id: 'vibrant_lime',
    name: 'Lime Green',
    description: 'Vibrant lime green',
    isDark: true,
    category: 'vibrant',
    colors: {
      primary: '#00ff00',
      secondary: '#00ff7f',
      background: '#001a00',
      surface: '#003300',
      foreground: '#ffffff',
      muted: '#99ff99',
      border: '#006600',
      success: '#00ff00',
      warning: '#ffff00',
      error: '#ff0000',
      accent: '#00ff7f',
    },
  },
  {
    id: 'vibrant_coral',
    name: 'Coral Reef',
    description: 'Coral reef colors',
    isDark: false,
    category: 'vibrant',
    colors: {
      primary: '#ff7f50',
      secondary: '#ff6347',
      background: '#fff5ee',
      surface: '#ffe4c4',
      foreground: '#1a1a1a',
      muted: '#666666',
      border: '#ffa07a',
      success: '#00ff00',
      warning: '#ff8c00',
      error: '#ff0000',
      accent: '#ff6347',
    },
  },
];

// Pastel Themes
const pastelThemes: Theme[] = [
  {
    id: 'pastel_soft_pink',
    name: 'Soft Pink',
    description: 'Soft pastel pink theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#f8bbd0',
      secondary: '#f48fb1',
      background: '#fce4ec',
      surface: '#f8bbd0',
      foreground: '#880e4f',
      muted: '#c2185b',
      border: '#f8bbd0',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#f48fb1',
    },
  },
  {
    id: 'pastel_soft_blue',
    name: 'Soft Blue',
    description: 'Soft pastel blue theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#bbdefb',
      secondary: '#90caf9',
      background: '#e3f2fd',
      surface: '#bbdefb',
      foreground: '#0d47a1',
      muted: '#1976d2',
      border: '#bbdefb',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#90caf9',
    },
  },
  {
    id: 'pastel_soft_green',
    name: 'Soft Green',
    description: 'Soft pastel green theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#c8e6c9',
      secondary: '#a5d6a7',
      background: '#e8f5e9',
      surface: '#c8e6c9',
      foreground: '#1b5e20',
      muted: '#388e3c',
      border: '#c8e6c9',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#a5d6a7',
    },
  },
  {
    id: 'pastel_soft_purple',
    name: 'Soft Purple',
    description: 'Soft pastel purple theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#e1bee7',
      secondary: '#ce93d8',
      background: '#f3e5f5',
      surface: '#e1bee7',
      foreground: '#4a148c',
      muted: '#7b1fa2',
      border: '#e1bee7',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#ce93d8',
    },
  },
  {
    id: 'pastel_soft_yellow',
    name: 'Soft Yellow',
    description: 'Soft pastel yellow theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#fff9c4',
      secondary: '#fff59d',
      background: '#fffde7',
      surface: '#fff9c4',
      foreground: '#f57f17',
      muted: '#f9a825',
      border: '#fff9c4',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#fff59d',
    },
  },
  {
    id: 'pastel_soft_orange',
    name: 'Soft Orange',
    description: 'Soft pastel orange theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#ffe0b2',
      secondary: '#ffcc80',
      background: '#fff3e0',
      surface: '#ffe0b2',
      foreground: '#e65100',
      muted: '#f57c00',
      border: '#ffe0b2',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#ffcc80',
    },
  },
  {
    id: 'pastel_soft_cyan',
    name: 'Soft Cyan',
    description: 'Soft pastel cyan theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#b2ebf2',
      secondary: '#80deea',
      background: '#e0f2f1',
      surface: '#b2ebf2',
      foreground: '#00838f',
      muted: '#0097a7',
      border: '#b2ebf2',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#80deea',
    },
  },
  {
    id: 'pastel_soft_red',
    name: 'Soft Red',
    description: 'Soft pastel red theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#ffcdd2',
      secondary: '#ef9a9a',
      background: '#ffebee',
      surface: '#ffcdd2',
      foreground: '#b71c1c',
      muted: '#d32f2f',
      border: '#ffcdd2',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#ef9a9a',
    },
  },
  {
    id: 'pastel_soft_teal',
    name: 'Soft Teal',
    description: 'Soft pastel teal theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#b2dfdb',
      secondary: '#80cbc4',
      background: '#e0f2f1',
      surface: '#b2dfdb',
      foreground: '#004d40',
      muted: '#00796b',
      border: '#b2dfdb',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#80cbc4',
    },
  },
  {
    id: 'pastel_soft_indigo',
    name: 'Soft Indigo',
    description: 'Soft pastel indigo theme',
    isDark: false,
    category: 'pastel',
    colors: {
      primary: '#c5cae9',
      secondary: '#9fa8da',
      background: '#e8eaf6',
      surface: '#c5cae9',
      foreground: '#1a237e',
      muted: '#283593',
      border: '#c5cae9',
      success: '#81c784',
      warning: '#ffb74d',
      error: '#ef5350',
      accent: '#9fa8da',
    },
  },
];

// Professional Themes
const professionalThemes: Theme[] = [
  {
    id: 'professional_corporate',
    name: 'Corporate Blue',
    description: 'Professional corporate blue',
    isDark: false,
    category: 'professional',
    colors: {
      primary: '#003366',
      secondary: '#0066cc',
      background: '#f5f5f5',
      surface: '#ffffff',
      foreground: '#000000',
      muted: '#666666',
      border: '#cccccc',
      success: '#00aa00',
      warning: '#ff9900',
      error: '#cc0000',
      accent: '#0066cc',
    },
  },
  {
    id: 'professional_dark_corporate',
    name: 'Dark Corporate',
    description: 'Professional dark corporate',
    isDark: true,
    category: 'professional',
    colors: {
      primary: '#4a90e2',
      secondary: '#357abd',
      background: '#1a1a1a',
      surface: '#2d2d2d',
      foreground: '#ffffff',
      muted: '#999999',
      border: '#404040',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#4a90e2',
    },
  },
  {
    id: 'professional_minimal',
    name: 'Minimal Pro',
    description: 'Minimal professional theme',
    isDark: false,
    category: 'professional',
    colors: {
      primary: '#1a1a1a',
      secondary: '#4a4a4a',
      background: '#ffffff',
      surface: '#f9f9f9',
      foreground: '#1a1a1a',
      muted: '#808080',
      border: '#e0e0e0',
      success: '#2ecc71',
      warning: '#f39c12',
      error: '#e74c3c',
      accent: '#4a4a4a',
    },
  },
  {
    id: 'professional_tech',
    name: 'Tech Dark',
    description: 'Tech-focused dark theme',
    isDark: true,
    category: 'professional',
    colors: {
      primary: '#00d4ff',
      secondary: '#0099ff',
      background: '#0a0e27',
      surface: '#1a1f3a',
      foreground: '#e0e0e0',
      muted: '#888888',
      border: '#2d3748',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#00d4ff',
    },
  },
  {
    id: 'professional_finance',
    name: 'Finance Green',
    description: 'Finance-focused green',
    isDark: false,
    category: 'professional',
    colors: {
      primary: '#1b5e20',
      secondary: '#2e7d32',
      background: '#f1f8e9',
      surface: '#ffffff',
      foreground: '#1b5e20',
      muted: '#558b2f',
      border: '#c5e1a5',
      success: '#2e7d32',
      warning: '#f57c00',
      error: '#c62828',
      accent: '#2e7d32',
    },
  },
  {
    id: 'professional_medical',
    name: 'Medical Blue',
    description: 'Medical-focused blue',
    isDark: false,
    category: 'professional',
    colors: {
      primary: '#0277bd',
      secondary: '#0288d1',
      background: '#e1f5fe',
      surface: '#ffffff',
      foreground: '#01579b',
      muted: '#0277bd',
      border: '#b3e5fc',
      success: '#00897b',
      warning: '#f57c00',
      error: '#d32f2f',
      accent: '#0288d1',
    },
  },
  {
    id: 'professional_creative',
    name: 'Creative Purple',
    description: 'Creative industry purple',
    isDark: false,
    category: 'professional',
    colors: {
      primary: '#6a1b9a',
      secondary: '#7b1fa2',
      background: '#f3e5f5',
      surface: '#ffffff',
      foreground: '#4a148c',
      muted: '#9c27b0',
      border: '#e1bee7',
      success: '#2e7d32',
      warning: '#f57c00',
      error: '#d32f2f',
      accent: '#7b1fa2',
    },
  },
  {
    id: 'professional_startup',
    name: 'Startup Orange',
    description: 'Startup-focused orange',
    isDark: false,
    category: 'professional',
    colors: {
      primary: '#e65100',
      secondary: '#f57c00',
      background: '#fff3e0',
      surface: '#ffffff',
      foreground: '#bf360c',
      muted: '#ff6f00',
      border: '#ffe0b2',
      success: '#2e7d32',
      warning: '#f57c00',
      error: '#d32f2f',
      accent: '#f57c00',
    },
  },
  {
    id: 'professional_education',
    name: 'Education Teal',
    description: 'Education-focused teal',
    isDark: false,
    category: 'professional',
    colors: {
      primary: '#00796b',
      secondary: '#00897b',
      background: '#e0f2f1',
      surface: '#ffffff',
      foreground: '#004d40',
      muted: '#009688',
      border: '#b2dfdb',
      success: '#2e7d32',
      warning: '#f57c00',
      error: '#d32f2f',
      accent: '#00897b',
    },
  },
  {
    id: 'professional_luxury',
    name: 'Luxury Gold',
    description: 'Luxury gold and black',
    isDark: true,
    category: 'professional',
    colors: {
      primary: '#d4af37',
      secondary: '#ffd700',
      background: '#1a1a1a',
      surface: '#2d2d2d',
      foreground: '#ffffff',
      muted: '#999999',
      border: '#404040',
      success: '#4ade80',
      warning: '#fbbf24',
      error: '#f87171',
      accent: '#d4af37',
    },
  },
];

// Export all themes
export const allThemes: Theme[] = [
  ...lightThemes,
  ...darkThemes,
  ...vibrantThemes,
  ...pastelThemes,
  ...professionalThemes,
];

export const themesByCategory = {
  light: lightThemes,
  dark: darkThemes,
  vibrant: vibrantThemes,
  pastel: pastelThemes,
  professional: professionalThemes,
};

export const getThemeById = (id: string): Theme | undefined => {
  return allThemes.find(theme => theme.id === id);
};

export const getThemesByCategory = (category: 'light' | 'dark' | 'vibrant' | 'pastel' | 'professional'): Theme[] => {
  return themesByCategory[category] || [];
};

export default allThemes;
